version: '2'

services:
    postgres-database:
        image: postgres:11
        container_name: postgres-canopus
        volumes:
          - ./db_data:/var/lib/postgresql/data
        environment:
          - POSTGRES_DB='postgres'
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=sudopostgres
          - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
          - "5432:5432"
